name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: node index.js
      - name: Run Tests
        run: npm test
      - name: Deploy to Local Demo
        run: |
          echo "Deploying to local demo environment..."
          mkdir -p ~/demo-deploy
          cp -r ./* ~/demo-deploy/
          cd ~/demo-deploy
          npm install --production || true
          nohup npm start &
          echo "Application deployed locally at ~/demo-deploy"